version: "3.8"

services:
  backend:
    build: ./server
    container_name: interviewlens-backend
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env

  frontend:
    build: ./client
    container_name: interviewlens-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend